GENCODE_GTF: /gscmnt/gc7210/dinglab/medseq/shared/TCGA/MC3/mbailey/ICGC_MC3/Data/gencode.v19.annotation.gtf.gz 
SAMPLES:
  exome_broadbed: /gscmnt/gc7210/dinglab/medseq/shared/TCGA/MC3/mbailey/ICGC_MC3/TCGAonlyData/exome.broadbed.maf
  genome_broadbed: /gscmnt/gc7210/dinglab/medseq/shared/TCGA/MC3/mbailey/ICGC_MC3/TCGAonlyData/genome.broadbed.maf

OVERLAPPED_SAMPLE_INFO: /gscmnt/gc7210/dinglab/medseq/shared/TCGA/MC3/mbailey/ICGC_MC3/Map/exome.genome.olap.stats.txt
WIG_BED_DIR: /gscmnt/gc7210/dinglab/medseq/shared/TCGA/MC3/mbailey/ICGC_MC3/CleanWigs/WigBeds
FAKE_ICGC46_WIG: /gscmnt/gc3024/dinglab/medseq/Noncoding_eQTL/ICGC_TCGA_comparison/wliang/icgc50/BAM2Wig/bed/fake_icgc46.wig
FAKE_ICGC46_WIG: /gscmnt/gc7210/dinglab/medseq/shared/TCGA/MC3/mbailey/ICGC_MC3/CleanWigs/fake_icgc46.wig.bed
BROAD_ROI_BED: /gscmnt/gc7210/dinglab/medseq/shared/TCGA/MC3/mbailey/SMG_20160403/input/GenROI/gaf_20111020+broad_wex_1.1_hg19.bed
