name: snake
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- bedtools=2.26.0=0
- dropbox=5.2.1=py36_0
- filechunkio=1.6=py36_0
- ftputil=3.2=py36_0
- pysftp=0.2.9=py36_0
- r-data.table=1.10.0=r3.3.1_1
- r-stringr=1.1.0=r3.3.1_0
- snakemake=3.12.0=py36_1
- urllib3=1.12=py36_0
- asn1crypto=0.22.0=py36_0
- cffi=1.10.0=py36_0
- cryptography=1.8.1=py36_0
- curl=7.52.1=0
- docutils=0.13.1=py36_0
- gsl=2.2.1=0
- icu=54.1=0
- idna=2.5=py36_0
- jbig=2.1=0
- jpeg=9b=0
- libgcc=4.8.5=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libtiff=4.0.6=3
- libxml2=2.9.4=0
- ncurses=5.9=10
- openssl=1.0.2k=2
- packaging=16.8=py36_0
- paramiko=2.1.2=py36_0
- pcre=8.39=1
- pip=9.0.1=py36_1
- psutil=5.2.2=py36_0
- pyasn1=0.2.3=py36_0
- pycparser=2.17=py36_0
- pyparsing=2.1.4=py36_0
- python=3.6.1=2
- pyyaml=3.12=py36_0
- readline=6.2=2
- requests=2.14.2=py36_0
- setuptools=27.2.0=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- wrapt=1.10.10=py36_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- r=3.3.1=r3.3.1_0
- r-base=3.3.1=0
- r-boot=1.3_18=r3.3.1_0
- r-class=7.3_14=r3.3.1_0
- r-cluster=2.0.4=r3.3.1_0
- r-codetools=0.2_14=r3.3.1_0
- r-foreign=0.8_66=r3.3.1_0
- r-kernsmooth=2.23_15=r3.3.1_0
- r-lattice=0.20_33=r3.3.1_0
- r-magrittr=1.5=r3.3.1_2
- r-mass=7.3_45=r3.3.1_0
- r-matrix=1.2_6=r3.3.1_0
- r-mgcv=1.8_12=r3.3.1_0
- r-nlme=3.1_128=r3.3.1_0
- r-nnet=7.3_12=r3.3.1_0
- r-plyr=1.8.4=r3.3.1_0
- r-rcpp=0.12.5=r3.3.1_0
- r-recommended=3.3.1=r3.3.1_0
- r-rpart=4.1_10=r3.3.1_0
- r-spatial=7.3_11=r3.3.1_0
- r-stringi=1.1.1=r3.3.1_0
- r-survival=2.39_4=r3.3.1_0

