name: autopipe
channels: !!python/tuple
- bioconda
- conda-forge
- defaults
dependencies:
- bioconda::bedops=2.4.20=0
- bioconda::bedtools=2.26.0=0
- bioconda::dropbox=5.2.1=py35_0
- bioconda::filechunkio=1.6=py35_0
- bioconda::ftputil=3.2=py35_0
- bioconda::pysftp=0.2.8=py35_0
- bioconda::snakemake=3.8.2=py35_0
- bioconda::urllib3=1.12=py35_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py35_0
- conda-forge::ca-certificates=2016.8.31=0
- conda-forge::certifi=2016.8.31=py35_0
- conda-forge::decorator=4.0.10=py35_0
- conda-forge::docutils=0.12=py35_0
- conda-forge::ipython=5.1.0=py35_1
- conda-forge::ipython_genutils=0.1.0=py35_0
- conda-forge::ncurses=5.9=9
- conda-forge::openssl=1.0.2h=2
- conda-forge::paramiko=1.17.2=py35_0
- conda-forge::pexpect=4.2.1=py35_0
- conda-forge::pickleshare=0.7.3=py35_0
- conda-forge::pip=8.1.2=py35_0
- conda-forge::prompt_toolkit=1.0.8=py35_0
- conda-forge::ptyprocess=0.5.1=py35_0
- conda-forge::pycrypto=2.6.1=py35_0
- conda-forge::pygments=2.1.3=py35_1
- conda-forge::python=3.5.2=2
- conda-forge::pyyaml=3.11=py35_0
- conda-forge::readline=6.2=0
- conda-forge::requests=2.11.1=py35_0
- conda-forge::setuptools=26.1.1=py35_0
- conda-forge::simplegeneric=0.8.1=py35_0
- conda-forge::six=1.10.0=py35_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=0
- conda-forge::traitlets=4.3.0=py35_0
- conda-forge::wcwidth=0.1.7=py35_0
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::wrapt=1.10.8=py35_0
- conda-forge::xz=5.2.2=0
- conda-forge::yaml=0.1.6=0
- conda-forge::zlib=1.2.8=3
- ecdsa=0.13=py35_0
- libgcc=5.2.0=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - prompt-toolkit==1.0.8
prefix: /gscuser/lwang/.pyenv/versions/miniconda3-latest/envs/autopipe

